sudo: true
language: node_js
node_js:
- '10'
script:
- "./deploy.sh"
branches:
  only:
  - master
install:
- npm install
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
env:
  global:
  - secure: Rh1nxhdXvyLriK1BgFRX7oSaodTciJ9YHNv+8MNAVMIJGWf3asgTvnEDD7cKP6+ovPZfifkXwjtMYslv/YGGITr0j8KTC9aFbxQoJ3L+ICjYPX90InKkNu6cILW+xV26Xq7Tnjzxdvs3oghTuPq/kIDwEofyxHNtHm1P4TF7lUiyV0OrKDDiiEN5vREd2iKhN62+ptFQN8c50sh8bz4j0J52WIbjcs1QEd8EwdzSTn8k7fYtL+SoXZ1inMNUZm6QvHq+q0w/51comBITFSqYDi9uNo2y06if8h6jL7JhIHWP8Vc2QoZxP2x/JcDHAAczwuqzXH4/MxAJso5NXG8nbKw/yk16eu4o6MO9bSBe/o47HXmToQofjvYqyItPz7SQ9hOs7CJUbhO2L/TOXewc3juZwECoKCWQQlGyT1Q3H2GBzru+zH4TOmtD63Losn0kwwlY9+D4DAN9L2Xk+1IWWhxuEc7cPU4HIwljNlsRHIE9mYefGwd3uad2wkYSKLrP8UfLUCeAxHtlfEEaKr/sP92wKNmWPRPa+k7xT73suBb2e4L11ZWJkRudVppB52I5bRCV42JuLa7Ywfs+5AlpCNUk4dl2yFMnUe7FtYdY+rKsBZ7Zm3Q1Ulo2mbuN0vyRlb62AsjrnR8eMYDxe+vtmfa+iVE4NFJss5LuwgDASdY=
  - secure: grV/fLVM1m9V2FSXKcbKoN9xMorTopUjztyHwnkl0M1RsF7iTtxKf0RpcmeFACZvis2L+m4N7aaS8RRpCUxaCe91TVZiUeVP4pfCb7uUDG/rl0HCOtpfp9Ovimq7j7J5N8rO08DRm6S/y3immvP5pHbOl13VaAlQ65+UI7CIBjEZTzSkQc7zlL9LIxG259IP1C99amGyBbbasfJMqpmPMwFMvxroVLibRjC3AMc4C/eOmhm/Wv2dD6nHWtEsYaSziQZ1y2ogGQ+7eLTCNRCCQL/U3+3dZ+NC/XQVabc/sSBtFmLnbLgGKm3wZ2kzzD6l0uHO9EpE9nhfKyHdY92ASPLNzkK1wnJZUuxqGvR5K0o1DosVWxH1wsLKVYV3EbILFMXenWQvBj7IuGOj7dFz5Hravmf0Q+l2/WPw5v1+6xpC0LjFvnO9R9zGHu9Jqmafwb/CZoBcOFaAmVhoH4hi8wKC2Kj17/l7C9cY5KdVCvNvWjDG5WdRL8W7kFcnqEoyZFaoCtv74uL0TkaVn6PdWK9Yx01aXaETrCQDMoCv/CsoMwxwTbHHWsN40+EjiMhZV7BcKW5Jvw7K7YWdz7pH2KR8+DvmTnSOwn9wfi6AgNxUpkqV53gbA8c6arSjo/omXgK1UFb9ZTLK41xypeOlrNXG06EC8kbgWMKf0KTnPwE=
  - secure: TAlzbpkSpPF8Gj9BdsQ1hjehXMwjNwWVouK0StoYps9yX24OTOqjRg2EYhTzf9PiWhNozwVIlEon4krzAkz6JGLSpkqUizPpD0tv/WcrugYR699NzA2c7k0KErMTv5nG5rsEp0t5wCzEKQcezWjrmM4TX3mdOvNdp+FH3YPQf2pjHKcpibdHumHf+bIICcs+olxjJqw7mnHJbQvRhUbk9K2J9/fSPFY9WZAxnhBMqYJfCBTRLhYUe8K9CFKNljSp5QMDWrEArwhW+tZm+RwtvE1HjtOFJybBrW62zqtSxBz1F2RlHOiKerNPTk2lbUFyZepG471rVU7+KtMcv3+vtsr9aMJO9OHpQKt2lXTBLI8/2P54A5w3rEhJNl7YUbECPzb7oQmMw7gYn8LvzXfYNdoCnpF5qulp4uh1XA7WHOCB1W4cKxS99rkjg+tc6WqJ/whJbdH/Sl0Hj4aVANTzX3zAqnY99YmruETj/dYa2PyUhUN4H9O9ICIChsBRZH5VjuIP6gVwGYo96a8wXg1SoJ4vJBqwSyYO1Eyvk/WKeqytGaEXvzzu52+fpviG4ytIpNUl3FAsM6V6xzXUaJtkjiVLZIj+oCDwY1lqm67kzNMonixtyigT/jzFUEc3uU0ntHv9LM0ulTYPxvi5aHq8tjCtQxDXUJejGekaGHOiWD4=
