sudo: true
language: node_js
node_js:
- '10'
script:
- chmod +x ./deploy.sh
branches:
  only:
  - master
install:
- npm install
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
env:
  global:
  - secure: Rh1nxhdXvyLriK1BgFRX7oSaodTciJ9YHNv+8MNAVMIJGWf3asgTvnEDD7cKP6+ovPZfifkXwjtMYslv/YGGITr0j8KTC9aFbxQoJ3L+ICjYPX90InKkNu6cILW+xV26Xq7Tnjzxdvs3oghTuPq/kIDwEofyxHNtHm1P4TF7lUiyV0OrKDDiiEN5vREd2iKhN62+ptFQN8c50sh8bz4j0J52WIbjcs1QEd8EwdzSTn8k7fYtL+SoXZ1inMNUZm6QvHq+q0w/51comBITFSqYDi9uNo2y06if8h6jL7JhIHWP8Vc2QoZxP2x/JcDHAAczwuqzXH4/MxAJso5NXG8nbKw/yk16eu4o6MO9bSBe/o47HXmToQofjvYqyItPz7SQ9hOs7CJUbhO2L/TOXewc3juZwECoKCWQQlGyT1Q3H2GBzru+zH4TOmtD63Losn0kwwlY9+D4DAN9L2Xk+1IWWhxuEc7cPU4HIwljNlsRHIE9mYefGwd3uad2wkYSKLrP8UfLUCeAxHtlfEEaKr/sP92wKNmWPRPa+k7xT73suBb2e4L11ZWJkRudVppB52I5bRCV42JuLa7Ywfs+5AlpCNUk4dl2yFMnUe7FtYdY+rKsBZ7Zm3Q1Ulo2mbuN0vyRlb62AsjrnR8eMYDxe+vtmfa+iVE4NFJss5LuwgDASdY=
